name: Deploy Connect Python SDK

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
        pip install -r requirements/sdk.txt
        pip install pytest-cov
        pip install twine
    - name: Linting
      run: |
        flake8 connect
    - name: Testing
      run: |
        pytest --cov-report=xml --cov=./connect
        sed -i "s/version='0.0.0'/version='${TRAVIS_TAG}'/g" setup.py
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
    - name: Fix coverage report for Sonar
      run: |
        sed -i 's/\/home\/runner\/work\/connect-python-sdk\/connect-python-sdk\//\/github\/workspace\//g' coverage.xml
    - name: SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*